// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ_fgDF9nSKwp8iuMC5BGll3g1XUg7KA0',
    appId: '1:1022818587337:web:56f44045c7ca007a917318',
    messagingSenderId: '1022818587337',
    projectId: 'quiz-app-d78ff',
    authDomain: 'quiz-app-d78ff.firebaseapp.com',
    storageBucket: 'quiz-app-d78ff.appspot.com',
    measurementId: 'G-9F68HGPJRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaJACAlTum6CBv0cDgIlWGa2NnGBQ0QcQ',
    appId: '1:1022818587337:android:47feebf3e7b000be917318',
    messagingSenderId: '1022818587337',
    projectId: 'quiz-app-d78ff',
    storageBucket: 'quiz-app-d78ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbHG43cV9arAn3mI3l6HhHS3SdQGmvvvg',
    appId: '1:1022818587337:ios:ecf748525d8c06f2917318',
    messagingSenderId: '1022818587337',
    projectId: 'quiz-app-d78ff',
    storageBucket: 'quiz-app-d78ff.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbHG43cV9arAn3mI3l6HhHS3SdQGmvvvg',
    appId: '1:1022818587337:ios:6012cd39340849a7917318',
    messagingSenderId: '1022818587337',
    projectId: 'quiz-app-d78ff',
    storageBucket: 'quiz-app-d78ff.appspot.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
